image: node:latest

stages:
- install
- test
- build
- deploy

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - .awcache/
  
install:
  stage: install
  only:
  - master
  script:
  - npm install

lint:
  stage: test
  dependencies:
  - install
  only:
  - master
  script:
  - npm run lint

test:
  stage: test
  dependencies:
  - install
  only:
  - master
  script:
  - echo "no test"

build:
  stage: build
  dependencies: 
  - install
  - test
  only:
  - master
  script:
  - npm run build
  artifacts:
    paths:
    - dist/

deploy:
  stage: deploy
  dependencies: 
  - install
  - test
  - build
  only:
  - master
  script:
  - echo "no deployment"
  
