image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  CONTAINER_DEPLOY_IMAGE: ${HEROKU_REGISTRY}/${HEROKU_PROJECT}/web

services:
  - docker:dind

before_script:
  - docker info
  - docker login -u $HEROKU_USER -p $HEROKU_KEY $HEROKU_REGISTRY
  - apk add --update curl && rm -rf /var/cache/apk/*

stages: 
  - build
  - test
  - deploy

build:
  stage: build
  only:
    - master
  script:
    - docker pull $CONTAINER_DEPLOY_IMAGE || true
    - docker build --cache-from $CONTAINER_DEPLOY_IMAGE -t $CONTAINER_DEPLOY_IMAGE .
    - docker push $CONTAINER_DEPLOY_IMAGE

deploy:
  stage: deploy
  only:
    - master
  script: 
    - chmod +x ./release.sh
    - ./release.sh $HEROKU_PROJECT
